### ISSUE TITLE
Pull requests don't self-close if you land your commit in a branch other than the default branch.

### ISSUE THREAD

**Issue by benhollander** [git-land/git-land#16]
My assumption is that github automagically closes tickets/pull requests when a commit with the proper description is merged into the default branch. Not sure if it's possible to do the same for branches other than the default branch.

**Comment by benhollander** [comment]
It looks like this would be possible through the github api, but that would likely add a lot of overhead to this project.

**Comment by lawnsea** [comment]
Yeah, this behavior is a bummer. GH should close the PR when it sees that commit message in the target branch of the PR.

> It looks like this would be possible through the github api, but that would likely add a lot of overhead to this project.

I agree. I think a webhook is probably the right way to fix this: https://help.github.com/articles/about-webhooks/.

**Comment by benhollander** [comment]
@lawnsea that seems reasonable. I'll look into it for our use-case.
There may be reason to add API interactions to this at some point, but I don't think that this issue is enough to warrant that.

**Comment by benhollander** [comment]
Looks like github started making this work on their own.

Great work everybody!

**Comment by lawnsea** [comment]
hooray!

**Comment by tiffting** [comment]
@benhollander, my PRs are not auto-closing against a non-master branch. :(

**Comment by benhollander** [comment]
:tableflip:
