### ISSUE TITLE
There is no error checking when pushing to remote

### ISSUE THREAD

**Issue by cwpage** [git-land/git-land#35]
There is no error checking when pushing to the remote branch.  If the push is rejected for some reason by the remote, git-land will continue to go on executing the post-land hook even though the push was not successful.

We should add error checking to the push to remote step.

**Comment by knksmith57** [comment]
Maybe as simple as adding that `exit_and_cleanup` call after the `git push $remote $target` here: https://github.com/git-land/git-land/blob/master/git-land#L164?

**Comment by cwpage** [comment]
Yeah that is what I'm thinking.

**Comment by lawnsea** [comment]
Yep, this is a bug. Good catch, @cwpage.

**Comment by lzilioli** [comment]
@lawnsea what is the status of this?

**Comment by lawnsea** [comment]
@lzilioli I need to land the patch. I was waiting to see if anyone had any comments and it fell off my radar. I'll do so tomorrow morning.
